version: 2

jobs:
    build:
        docker:
            - image: hlapp/rpopgen
        steps:
            - checkout
            - run: make ci-deploy
            - persist_to_workspace:
                root: archive
                paths:
                    - .

    deploy:
        docker:
            - image: buildpack-deps:16.04-scm
        steps:
            - checkout
            - attach_workspace:
                at: /tmp/archive
            - add_ssh_keys:
                fingerprints:
                    - "04:32:c8:3e:0f:a9:5f:cf:d1:73:2f:5f:13:35:32:a8"
            - run: |
                git config user.name "PopgenInfo CI Build"
                git config user.email "ci-build@popgen.nescent.org"
                git checkout gh-pages
                rm -r *
                git checkout gh-pages -- CNAME
                tar xvf /tmp/archive/site.tar
                git add --all
                git commit -m "Website rebuild"
                git push origin gh-pages
                git checkout master

workflows:
    version: 2

    build_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        ignore: gh-pages
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
    weekly:
        triggers:
            - schedule:
                cron: "0 7 * * 2"
                filters:
                    branches:
                        only: 
                            - master
        jobs:
            - build:
                filters:
                    branches:
                        ignore: gh-pages

